src/cooking/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipies/", include("recipies.urls")),
    path("ingredients/",include("ingredients.urls")),
    path("shoppingList/", include("shoppingList.urls")),
]

src/home/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("ingredients/", include("ingredients.urls")),
    path("shoppingList/", include("shoppingList.urls")),
    path("recipies/", include("recipies.urls")),
]

src/ingredients/urls.py
from django.urls import path
from . import views

app_name = "ingredients"
urlpatterns =[
    path("", views.List.as_view(), name="list"),
    path("add/", views.Add.as_view(), name="add"),
    path("addToShoppingList/", views.addToShoppingList, name="addToShoppingList"),
]

src/recipies/urls.py
from django.urls import path
from . import views

app_name="recipies"
urlpatterns = [
    path("", views.IndexView.as_view(), name="list"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("delete/<int:recipe_id>", views.delete, name="delete"),
    path("createCategory/", views.CreateCategory.as_view(), name="createCategory"),
    path("getRecipeFromAPI", views.get_recipe_from_API, name="getRecipeFromAPI")
]

src/shoppingList/urls.py
from django.urls import path
from . import views

app_name= "shoppingList"
urlpatterns = [
    path("", views.ShoppingListView.as_view(), name="list"),
    path("createListWithIngredients", views.add_ingredients_to_session,
         name='createListWithIngredients'),
    path("createList", views.create_list, name='createList'),
    path("<int:pk>/", views.ShoppingListDetail.as_view(), name="detail"),
    path("<int:shoppinglist_id>/delete", views.delete_list, name="delete"),
    path("<int:shoppinglist_id>/downloadList", views.download_list, name="downloadList"),
]

src/ingredients/models.py
from django.db import models

class Ingredient(models.Model):
    name = models.CharField(max_length=100)
    kcal_per_100g = models.IntegerField(default=0)

    def __str__(self):
        return self.name

src/recipies/models.py
from django.db import models
from ingredients.models import Ingredient

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Recipe(models.Model):
    title = models.CharField(max_length=200)
    ingredients = models.ManyToManyField(Ingredient)
    instruction = models.TextField(max_length=500)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

src/shoppingList/models.py
from django.db import models
from ingredients.models import Ingredient

class ShoppingList(models.Model):
    name = models.CharField(max_length=100)
    ingredients = models.ManyToManyField(Ingredient)

    def __str__(self):
        return self.name

src/shoppingList/forms.py
from django import forms
from .models import ShoppingList, Ingredient


class ShoppingListForm(forms.ModelForm):
    class Meta:
        model = ShoppingList
        fields = ['name', 'ingredients']

    name = forms.CharField(
        max_length=100,
        required=True,
    )

    ingredients = forms.ModelMultipleChoiceField(
        queryset=Ingredient.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

src/home/views.py
from django.shortcuts import render
from django.shortcuts import render


def home(req):
    return render(req, "home.html")

src/ingredients/views.py
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views import generic
from .models import Ingredient
from shoppingList.models import ShoppingList

class Add(generic.CreateView):
    fields = ["name", "kcal_per_100g"]
    model = Ingredient
    success_url = reverse_lazy("ingredients:list")

class List(generic.ListView):
    model = Ingredient


def addToShoppingList(request):
    selected_ingredients = request.POST.getlist("ingredient")
    if not selected_ingredients:
        return HttpResponseRedirect(reverse_lazy("shoppingList:createList"))
    else:
    #    shopping_list = ShoppingList(name="NewList")
     #   shopping_list.save()
      #  for ingredient in selected_ingredients:
       #     shopping_list.ingredients.add(ingredient)
        return HttpResponseRedirect(reverse_lazy("shoppingList:createList"))

src/recipies/views.py
from django.views import generic
from django.urls import reverse_lazy
from ingredients.models import Ingredient
from .models import Recipe, Category
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
import requests


class IndexView(generic.ListView):
    model = Recipe


class DetailView(generic.DetailView):
    model = Recipe


class CreateView(generic.edit.CreateView):
    model = Recipe
    fields = ["title", "ingredients", "instruction", "category"]
    success_url = reverse_lazy('recipies:list')


def delete(req, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    recipe.delete()
    return HttpResponseRedirect(reverse_lazy("recipies:list"))


class CreateCategory(generic.CreateView):
    model = Category
    template_name = 'category_form.html'
    fields = ["name"]
    success_url = reverse_lazy("recipies:list")


def get_recipe_from_API(req):
    try:
        response = requests.get(
            "https://www.themealdb.com/api/json/v1/1/random.php")
        data = response.json()['meals'][0]
    except (requests.exceptions.RequestException, KeyError, IndexError) as e:
        print(f"Error during get {e}.")
        return redirect("recipies:list")

    title = data['strMeal']
    instructions = data['strInstructions']
    category, _ = Category.objects.get_or_create(name=data['strCategory'])

    all_ingredients = [k for k in data.keys() if k.startswith('strIngredient')]
    ingredients_names = [data[ing] for ing in all_ingredients if data[ing]]
    ingredients = []
    for name in ingredients_names:
        # TODO: bulk_create or get_or_create?
        ingredient, _= Ingredient.objects.get_or_create(name=name)
        ingredients.append(ingredient.id)

    recipe = Recipe.objects.create(
        title=title, instruction=instructions, category=category)
    recipe.ingredients.set(ingredients)
    return redirect("recipies:detail", pk=recipe.id)

src/shoppingList/views.py
import json
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.http import HttpResponseRedirect
from .models import ShoppingList, Ingredient
from .forms import ShoppingListForm
# Create your views here.

class ShoppingListView(generic.ListView):
    model = ShoppingList

def create_list(request):
    if request.method == "POST":
        form = ShoppingListForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy("shoppingList:list"))

    selected_ingredients = request.session.get('selected_ingredients', [])
    form = ShoppingListForm(initial={
                      'ingredients':Ingredient.objects.filter(id__in=selected_ingredients)
    })

    request.session.pop('selected_ingredients', None)
    return render(request, "shoppingList/shoppinglist_form.html", {'form': form})


def add_ingredients_to_session(request):
    if request.method == "POST":
        selected_ingredients = request.POST.getlist("ingredient")
        request.session['selected_ingredients'] = selected_ingredients
        return redirect('shoppingList:createList')

class ShoppingListDetail(generic.DetailView):
    model = ShoppingList
    fields = ["name", "ingredients"]


def delete_list(req, shoppinglist_id):
    list_to_delete = get_object_or_404(ShoppingList, pk=shoppinglist_id)
    list_to_delete.delete()
    return HttpResponseRedirect(reverse_lazy("shoppingList:list"))


def download_list(request, shoppinglist_id):
    shopping_list = ShoppingList.objects.get(id=shoppinglist_id)
    ingredients = shopping_list.ingredients.all()

    data = json.dumps({
        "List name: ": shopping_list.name,
        "Ingredients: ": [ing.name for ing in list(ingredients)]
    }, indent = 4)

    response = HttpResponse(data, content_type="text/plain")
    filename = shopping_list.name + "_list.txt"
    response['Content-Disposition']= f'attachment; filename="{filename}"'

    return response

src/ingredients/templates/ingredients/category_form.html
<form method="POST">
    {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Add category</button>
    </form>

src/recipies/templates/recipies/recipe_detail.html
<a href="{% url 'recipies:list' %}"><button>Go back to recipies list</button></a>
<form action= "{% url 'recipies:delete' recipe.id %}" method="POST">
{% csrf_token %}
<h1>Recipe: {{ recipe.title }}</h1>
<h2>Ingredients: {{ recipe.ingredients.all|join:", " }}</h2>
<h2>Instruction: </h2>
<h3>{{ recipe.instruction}}</h3>
<br>
<button type="submit" name="delete">Delete</button></a>
</form>

src/templates/category_form.html
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add category</button>
</form>

src/templates/home.html
{% block content %}
  <h1>Cooking App</h1>
  <p>Check out all our <a href="recipies/">recipies</a>.</p>
  <p>Here are available <a href="ingredients/">ingredients</a>.</p>
  <p>You can view and create <a href="shoppingList/">shopping lists</a> as well.</p>
{% endblock %}

src/templates/ingredients/ingredient_form.html
<form method="POST">
{% csrf_token %}
    {{ form.as_p }}
<button type="submit">Add ingredient</button>
</form>

src/templates/ingredients/ingredient_list.html
<form action="{% url 'shoppingList:createListWithIngredients' %}" method="post">
    {% csrf_token %}
    <ul>
    {% for ingredient in object_list %}
    <input type="checkbox" name ="ingredient" value="{{ ingredient.id }}"> {{ ingredient.name }} <br>
    {% empty %}
    <li>No ingredients yet.</li>
    {% endfor %}<br>
    <button type="button" onclick="location.href='{% url 'ingredients:add' %}'" >Add missing ingredient</button>
    <button type="submit" value="addToShoppingList">Add to shopping list</button>
</ul>
</form>

src/templates/recipies/recipe_detail.html
<form action= "{% url 'recipies:delete' recipe.id %}" method="POST">
{% csrf_token %}
<h1>Recipe: {{ recipe.title }}</h1>
<h2>Ingredients: {{ recipe.ingredients.all|join:", " }}</h2>
<h2>Instruction: </h2>
<h3>{{ recipe.instruction}}</h3>
<br>
<button type="submit" name="delete">Delete</button></a>
</form>

src/templates/recipies/recipe_form.html
<form method="POST">
    {% csrf_token %}
  {{ form.as_p}}
  <input type="submit" value="Save">
  <input type="button" value="Reset" id="resetBtn" onClick="this.form.reset()" />
</form>
<a href="{% url 'recipies:createCategory' %}"><button>Create Category</button></a>

src/templates/recipies/recipe_list.html
<h1>Recipies</h1>
<ul>
{% for recipe in object_list %}
<li><a href="{% url 'recipies:detail' recipe.id %}">{{ recipe.title }}</a></li>
{% empty %}
    <li>No recipies yet.</li>
{% endfor %}
<br>
<a href="{% url 'recipies:create' %}"><button>Create</button></a>
<a href="{% url 'recipies:getRecipeFromAPI' %}"><button>Get random recipe</button></a>
</ul>

src/templates/shoppingList/shoppinglist_detail.html
<h1>{{ shoppinglist.name }}</h1>
{% for ingredient in shoppinglist.ingredients.all %} 
<br>{{ ingredient.name }}
{% endfor %}<br>
<button type="button" onclick="location.href='{% url 'shoppingList:downloadList' shoppinglist.id %}'"> Download </button>
<button type="button" onclick="location.href='{% url 'shoppingList:delete' shoppinglist.id %}'">Delete List</button>

src/templates/shoppingList/shoppinglist_form.html
<form method="POST">
{% csrf_token %}
{{ form.as_p}}
<input type="submit" value="Save">
</form>

src/templates/shoppingList/shoppinglist_list.html
<h1>Shopping lists</h1>
{% for list in object_list %}
    <a href="{% url 'shoppingList:detail' list.id %}"> {{ list.name }} </a> <br>
{% endfor %}
<button type="button" onclick="location.href='{% url 'shoppingList:createList' %}'">Create List</button>